### ISSUE TITLE
Better error messaging for failed requests 

### ISSUE THREAD

**Issue by mckdemps** [10up/debug-bar-elasticpress#28]
**Is your enhancement related to a problem? Please describe.**

**Describe the solution you'd like**

We need to interpret log files for failed requests and instruct the user what meta data needs to be added to the index. 

**Designs**

**Describe alternatives you've considered**

**Additional context**

**Comment by felipeelia** [comment]
Some initial scenarios we can capture:
- post_date_gmt being a text field => It indicates a sync is needed (deleting the index and saving a post should trigger this error)
- sorting on a field that is not indexed

We can start with an array indexed by a regular expression and valued by the message to be displayed. The regex should capture important info and feed it to the message (if it failed due to a meta field, that field should be present in the message)

**Comment by felipeelia** [comment]
This should now rely on the functionality built in the main plugin ([here](https://github.com/10up/ElasticPress/blob/4.4.0/includes/classes/StatusReport/FailedQueries.php#L147)). Probably some change will be needed there, so we can reuse it here.
